name: LÖVE Potion

on:
  push:
    branches:
      - dev/3.0
  pull_request:

jobs:
  first:
    name: 3DS
    runs-on: ubuntu-latest

    container:
      image: docker://devkitpro/devkitarm
      options: --cpus 2

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: /opt/devkitpro/portlibs/3ds/bin/arm-none-eabi-cmake -S . -B build ; make -C build

      - id: commit
        uses: pr-mpt/actions-commit-hash@v1

      - uses: actions/upload-artifact@v2
        with:
          name: Nintendo 3DS-${{ steps.commit.outputs.short }}
          path: |
            build/*.elf
            build/*.3dsx

  second:
    name: Switch
    runs-on: ubuntu-latest

    container:
      image: docker://devkitpro/devkita64
      options: --cpus 2

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: /opt/devkitpro/portlibs/switch/bin/aarch64-none-elf-cmake -S . -B build ; make -C build

      - id: commit
        uses: pr-mpt/actions-commit-hash@v1

      - uses: actions/upload-artifact@v2
        with:
          name: Nintendo Switch-${{ steps.commit.outputs.short }}
          path: |
            build/*.elf
            build/*.nro

  third:
    name: Wii U
    runs-on: ubuntu-latest

    container:
      image: docker://devkitpro/devkitppc
      options: --cpus 2

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: /opt/devkitpro/portlibs/wiiu/bin/powerpc-eabi-cmake -S . -B build ; make -C build

      - id: commit
        uses: pr-mpt/actions-commit-hash@v1

      - uses: actions/upload-artifact@v2
        with:
          name: Nintendo Wii U-${{ steps.commit.outputs.short }}
          path: |
            build/*.elf
            build/*.rpx
            build/*.wuhb
